/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.EmprestimoDAO;
import Controller.LivroDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gutyr
 */
public class LivroTable extends javax.swing.JFrame {

    /**
     * Creates new form LivroTable
     */
    LivroDAO ld = new LivroDAO(); 
    public LivroTable() {
        initComponents();
        popularTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableLiv = new javax.swing.JTable();
        btLivAlu = new javax.swing.JButton();
        btTodosLiv = new javax.swing.JButton();
        btLivDisp = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        btLivGen = new javax.swing.JButton();
        btLivAut = new javax.swing.JButton();
        btLivNome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tabela de Livros");

        tableLiv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Gênero", "Edição", "Editora", "Ano de Lançamento", "Autor", "Está Alugado"
            }
        ));
        jScrollPane1.setViewportView(tableLiv);

        btLivAlu.setText("Mostrar Livros Alugados");
        btLivAlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLivAluActionPerformed(evt);
            }
        });

        btTodosLiv.setText("Mostrar Todos os Livros");
        btTodosLiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTodosLivActionPerformed(evt);
            }
        });

        btLivDisp.setText("Mostrar Livros não alugados");
        btLivDisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLivDispActionPerformed(evt);
            }
        });

        btLivGen.setText("Pesquisar por Genêro");
        btLivGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLivGenActionPerformed(evt);
            }
        });

        btLivAut.setText("Pesquisar por Autor");
        btLivAut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLivAutActionPerformed(evt);
            }
        });

        btLivNome.setText("Pesquisar por Nome");
        btLivNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLivNomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btLivGen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btLivAut)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btLivNome))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btTodosLiv, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btLivAlu)
                        .addGap(18, 18, 18)
                        .addComponent(btLivDisp)
                        .addGap(62, 62, 62))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLivGen)
                    .addComponent(btLivAut)
                    .addComponent(btLivNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btTodosLiv, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLivAlu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLivDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btTodosLivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTodosLivActionPerformed
        popularTabela();
    }//GEN-LAST:event_btTodosLivActionPerformed

    private void btLivAluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLivAluActionPerformed
        List<Object[]> livros = ld.selecionarLivroAlugados(); 
        DefaultTableModel modeloTabela = (DefaultTableModel) tableLiv.getModel();
        modeloTabela.setRowCount(0);

        // Adicionando os dados ao modelo
        for (Object[] livro : livros) {
            modeloTabela.addRow(livro);
        }
    }//GEN-LAST:event_btLivAluActionPerformed

    private void btLivDispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLivDispActionPerformed
        List<Object[]> livros = ld.selecionarLivDisp(); 
        DefaultTableModel modeloTabela = (DefaultTableModel) tableLiv.getModel();
        modeloTabela.setRowCount(0);

        // Adicionando os dados ao modelo
        for (Object[] livro : livros) {
            modeloTabela.addRow(livro);
        }
    }//GEN-LAST:event_btLivDispActionPerformed

    private void btLivGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLivGenActionPerformed
        List<Object[]> livros = ld.selecionarLivGenero(jTextField1.getText()); 
        DefaultTableModel modeloTabela = (DefaultTableModel) tableLiv.getModel();
        modeloTabela.setRowCount(0);

        // Adicionando os dados ao modelo
        for (Object[] livro : livros) {
            modeloTabela.addRow(livro);
        }
    }//GEN-LAST:event_btLivGenActionPerformed

    private void btLivAutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLivAutActionPerformed
        List<Object[]> livros = ld.selecionarLivAutor(jTextField1.getText()); 
        DefaultTableModel modeloTabela = (DefaultTableModel) tableLiv.getModel();
        modeloTabela.setRowCount(0);

        // Adicionando os dados ao modelo
        for (Object[] livro : livros) {
            modeloTabela.addRow(livro);
        }
    }//GEN-LAST:event_btLivAutActionPerformed

    private void btLivNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLivNomeActionPerformed
        List<Object[]> livros = ld.selecionarLivNome(jTextField1.getText()); 
        DefaultTableModel modeloTabela = (DefaultTableModel) tableLiv.getModel();
        modeloTabela.setRowCount(0);

        // Adicionando os dados ao modelo
        for (Object[] livro : livros) {
            modeloTabela.addRow(livro);
        }
    }//GEN-LAST:event_btLivNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LivroTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LivroTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LivroTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LivroTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LivroTable().setVisible(true);
            }
        });
    }
    
        public void popularTabela(){
        List<Object[]> livros = ld.buscarLivros(); 
        DefaultTableModel modeloTabela = (DefaultTableModel) tableLiv.getModel();
        modeloTabela.setRowCount(0);

        // Adicionando os dados ao modelo
        for (Object[] livro : livros) {
            modeloTabela.addRow(livro);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLivAlu;
    private javax.swing.JButton btLivAut;
    private javax.swing.JButton btLivDisp;
    private javax.swing.JButton btLivGen;
    private javax.swing.JButton btLivNome;
    private javax.swing.JButton btTodosLiv;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tableLiv;
    // End of variables declaration//GEN-END:variables
}
