/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
/**
 *
 * @author Victor
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itOpenLivros = new javax.swing.JMenuItem();
        itOpenUser = new javax.swing.JMenuItem();
        itOpenEmp = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itOpenRelEmp = new javax.swing.JMenuItem();
        itOpenRelLiv = new javax.swing.JMenuItem();
        itOpenRelUs = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bibliotecagem Simples");

        jMenu1.setText("Cadastros");

        itOpenLivros.setText("Cadastro de Livros");
        itOpenLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itOpenLivrosActionPerformed(evt);
            }
        });
        jMenu1.add(itOpenLivros);

        itOpenUser.setText("Cadastro de Usuarios");
        itOpenUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itOpenUserActionPerformed(evt);
            }
        });
        jMenu1.add(itOpenUser);

        itOpenEmp.setText("Cadastro de Empréstimos");
        itOpenEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itOpenEmpActionPerformed(evt);
            }
        });
        jMenu1.add(itOpenEmp);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Relatórios");

        itOpenRelEmp.setText("Relatório de Empreéstimos");
        itOpenRelEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itOpenRelEmpActionPerformed(evt);
            }
        });
        jMenu2.add(itOpenRelEmp);

        itOpenRelLiv.setText("Relatório de Livro");
        itOpenRelLiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itOpenRelLivActionPerformed(evt);
            }
        });
        jMenu2.add(itOpenRelLiv);

        itOpenRelUs.setText("Relatorio de Usuários");
        itOpenRelUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itOpenRelUsActionPerformed(evt);
            }
        });
        jMenu2.add(itOpenRelUs);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itOpenLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itOpenLivrosActionPerformed
        LivroGUI lg = new LivroGUI();
        lg.setVisible(true);
        
    }//GEN-LAST:event_itOpenLivrosActionPerformed

    private void itOpenUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itOpenUserActionPerformed
        UsuarioGUI ug = new UsuarioGUI();
        ug.setVisible(true);
    }//GEN-LAST:event_itOpenUserActionPerformed

    private void itOpenEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itOpenEmpActionPerformed
        EmprestimoGUI eg = new EmprestimoGUI();
        eg.setVisible(true);
    }//GEN-LAST:event_itOpenEmpActionPerformed

    private void itOpenRelEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itOpenRelEmpActionPerformed
        EmprestimoTable et = new EmprestimoTable();
        et.setVisible(true);
    }//GEN-LAST:event_itOpenRelEmpActionPerformed

    private void itOpenRelLivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itOpenRelLivActionPerformed
        LivroTable lt = new LivroTable();
        lt.setVisible(true);
    }//GEN-LAST:event_itOpenRelLivActionPerformed

    private void itOpenRelUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itOpenRelUsActionPerformed
        UsuarioTable ut = new UsuarioTable();
        ut.setVisible(true);
    }//GEN-LAST:event_itOpenRelUsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itOpenEmp;
    private javax.swing.JMenuItem itOpenLivros;
    private javax.swing.JMenuItem itOpenRelEmp;
    private javax.swing.JMenuItem itOpenRelLiv;
    private javax.swing.JMenuItem itOpenRelUs;
    private javax.swing.JMenuItem itOpenUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
